apiVersion: apps/v1
kind: Deployment
metadata:
  name: walidur-rahman-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: walidur-rahman-app
  template:
    metadata:
      labels:
        app: walidur-rahman-app
    spec:
      containers:
      - name: walidur-rahman-app
        image: mdwalidur/walidur-rahman-app:latest
        ports:
        - containerPort: 8080
