apiVersion: v1
kind: Service
metadata:
  name: walidur-rahman-service
spec:
  type: NodePort
  selector:
    app: walidur-rahman-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 32000  # Fixed port
